### PR TITLE
feat(exports): Make It Easier To Import Resource Into Other Resources

### PR DESCRIPTION
**Pull request by Archangelza1**
So This Allows Users Instead of typing

`exports["bt-target"]:AddPolyzone()`

they can now just

`targeting = exports["bt-target"]:FetchExports()`

Now they will be able to use any function via the targeting object for example

`targeting:AddPolyzone()`

### CODE REVIEW

**Comment by Archangelza1** [comment]
Awesome thanks

**Comment by BerkieBb** [comment]
@Archangelza1 I don't understand much about the self property so I don't know what use it brings for the function but I'm guessing it's for the double colon to work?

**Comment by BerkieBb** [comment]
I guess I could also look it up, I found it and yeah it's that, learnt something new 😄

**Comment by Archangelza1** [comment]
Yea its used for the double colon and also if you want to call it inside a function thats in the Exports object you can use 

`self:<function>()`

**Pull request merged**
